---
- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: ensure the latest list of packages are installed
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - httpd
      - httpd-tools
      - php

- name: deploy apache config file
  template:
    src: files/server-status.conf
    dest: /etc/httpd/conf.d/server-status.conf
  notify:
    - restart apache

- name: deploy php document to DocumentRoot
  template:
    src: files/info.php
    dest: /var/www/html/info.php

- name: deploy html document to DocumentRoot
  template:
    src: templates/index.html.j2
    dest: /var/www/html/index.html

- name: ensure apache is running
  service:
    name: httpd
    state: started
